apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    open-cluster-management.io/policy-set: openshift-plus
  name: binding-openshift-plus-hub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "3"
placementRef:
  name: placement-openshift-plus-hub
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: openshift-plus-hub
  kind: PolicySet
  apiGroup: policy.open-cluster-management.io
