apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-odf-ssl-certificates
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: odf-ssl-certificate-management
    app.kubernetes.io/component: placement
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "4"
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
    - key: cluster.open-cluster-management.io/clusterset
      operator: Exists
    - key: purpose
      operator: In
      values: ["regionalDR"]
    - key: vendor
      operator: In
      values: ["OpenShift"]
    - key: name
      operator: NotIn
      values: ["local-cluster"]
